import React from 'react'

export default function Profile() {
  return (
    <div>
      <h1>Profile</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime iusto assumenda molestiae saepe id autem totam esse aperiam error, atque itaque consectetur nihil tempore qui neque distinctio facere excepturi nam unde repellendus voluptatem quibusdam exercitationem ab? Ad itaque repellendus iure nam, harum provident non aut nihil quaerat omnis iste. Quasi distinctio sit neque aperiam blanditiis. Tempore beatae laudantium dolorum exercitationem quam quibusdam nobis reprehenderit consequatur, obcaecati voluptatibus repudiandae, facilis neque aperiam cum quas eveniet possimus? Nobis nulla error voluptates provident ut nisi exercitationem minus! Repellat maxime distinctio alias ea totam id nihil, necessitatibus commodi odio error quis quisquam amet magni mollitia quo cum sint repudiandae quibusdam esse saepe. Impedit ipsam illum libero dolores nihil quidem quasi laborum totam quo in ea sint sequi autem recusandae officia facilis dicta, placeat saepe? Velit, atque ratione dignissimos esse qui corporis consequuntur doloribus aliquam officia veritatis nisi quibusdam quos blanditiis omnis, neque obcaecati. Officiis similique dolor aliquam doloremque cum tempora labore voluptatum voluptatibus velit exercitationem, non debitis, nemo obcaecati! Doloremque nihil temporibus aperiam optio, nostrum ullam nam exercitationem vero architecto. Omnis in earum commodi minus? Hic quasi facilis optio obcaecati enim voluptatem aut aspernatur quos, maiores nihil sunt id maxime! Quas dolore soluta dicta!</p>
      <h1>Profile</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime iusto assumenda molestiae saepe id autem totam esse aperiam error, atque itaque consectetur nihil tempore qui neque distinctio facere excepturi nam unde repellendus voluptatem quibusdam exercitationem ab? Ad itaque repellendus iure nam, harum provident non aut nihil quaerat omnis iste. Quasi distinctio sit neque aperiam blanditiis. Tempore beatae laudantium dolorum exercitationem quam quibusdam nobis reprehenderit consequatur, obcaecati voluptatibus repudiandae, facilis neque aperiam cum quas eveniet possimus? Nobis nulla error voluptates provident ut nisi exercitationem minus! Repellat maxime distinctio alias ea totam id nihil, necessitatibus commodi odio error quis quisquam amet magni mollitia quo cum sint repudiandae quibusdam esse saepe. Impedit ipsam illum libero dolores nihil quidem quasi laborum totam quo in ea sint sequi autem recusandae officia facilis dicta, placeat saepe? Velit, atque ratione dignissimos esse qui corporis consequuntur doloribus aliquam officia veritatis nisi quibusdam quos blanditiis omnis, neque obcaecati. Officiis similique dolor aliquam doloremque cum tempora labore voluptatum voluptatibus velit exercitationem, non debitis, nemo obcaecati! Doloremque nihil temporibus aperiam optio, nostrum ullam nam exercitationem vero architecto. Omnis in earum commodi minus? Hic quasi facilis optio obcaecati enim voluptatem aut aspernatur quos, maiores nihil sunt id maxime! Quas dolore soluta dicta!</p>
    </div>
  )
}
